### ISSUE TITLE
Request to update tools

### ISSUE THREAD

**Issue by YorkWaugh** [apk-spectrum/apk-spectrum-core#3]
https://github.com/skylot/jadx/releases/tag/v1.4.7
https://github.com/pxb1988/dex2jar/releases/tag/v2.4
It seems that there are newer versions of the above tools. Could you please follow up on these updates?

**Comment by YorkWaugh** [comment]
BTW, https://github.com/apk-spectrum/apk-spectrum-core/tree/master/src/main/resources/icons/logo
The resolution of r.png and subsequent logos seems not to be 150x150, and the overly large images seem to cause display errors.
![PixPin_2024-04-02_17-31-32](https://github.com/apk-spectrum/apk-spectrum-core/assets/67750590/128bd023-730b-4b4a-97db-6bedff1d767d)
![PixPin_2024-04-02_17-31-47](https://github.com/apk-spectrum/apk-spectrum-core/assets/67750590/620e6aae-e6c2-48c5-88af-64ed838cb71b)

**Comment by sunggyu-kam** [comment]
I updated tools.
I also fixed the layout issue in the apk-scanner project.(72d0b22)
